version: "3"

services:
  server:
    container_name: app_server
    build: ./server
    ports:
      - 9000:9000
    depends_on:
      - mysql

  swagger_ui:
    container_name: swagger_ui
    image: swaggerapi/swagger-ui
    ports:
      - 80:8080

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/etc/mysql/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
